---
apiVersion: v1
kind: Service
metadata:
  name: obfs4-bridge
spec:
  type: LoadBalancer
  ports:
  - name: or-port
    port: 5893 
    targetPort: 58930
  - name: pt-port
    port: 5894 
    targetPort: 58941
  selector:
    app: obfs4-bridge
---
apiVersion: v1
kind: Service
metadata:
  name: squid-proxy
spec:
  type: LoadBalancer
  ports:
  - port: 3128
    targetPort: 3128
  selector:
    app: squid-proxy

